
[dataset_training]
train_path = "../assignment_1/assignment_1/input_dir/train"
valid_path = "../assignment_1/assignment_1/input_dir/valid"
architecture = "vgg"
max_epochs = 200
n_layers = 3
batch_size = 64
in_channels = 1
out_channels = 1
base_channels = 32
n_conv_sections = 2
input_shape = 28
dropout = 0
dropout_factor = 0.3


[dataset_testing]
