
[dataset_training]
train_path = "../assignment_1/assignment_1/input_dir/train"
valid_path = "../assignment_1/assignment_1/input_dir/valid"
save_model_path = "../assignment_1/assignment_1/output_dir/saved_model/vgg"
log_dir = "../assignment_1/assignment_1/output_dir/logger/vgg"
learning_rate = 0.001 # 0.01, 0.001, 0.0001
momentum = 0.95 # 0.5, 0.9, 0.99
architecture = "ensemble" # vgg, ensemble, locally_connected
max_epochs = 100
batch_size = 64 # 16, 32, 64 
in_channels = 1
out_channels = 10
base_channels = 8
n_layers = 2
input_shape = 16
dropout = 0
dropout_factor = 0.3


[dataset_testing]
