
[dataset_training]
train_path = "../assignment_1/assignment_1/input_dir/train"
valid_path = "../assignment_1/assignment_1/input_dir/valid"
save_model_path = "../assignment_1/assignment_1/output_dir/saved_model/ensemble"
log_dir = "../assignment_1/assignment_1/output_dir/logger/Ensemble"
learning_rate = 0.001  # 0.01 0.001 0.0001
momentum = 0.95 # 0.5 0.9 0.99
architecture = "ensemble" # vgg locally_connected ensemble
params = "kaimeng_normal" # normal uniform xavier_normal xavier_uniform kaimeng_normal kaimeng_uniform
max_epochs = 100
batch_size = 64 # 16 32 64
in_channels = 1
out_channels = 10
base_channels = 8
n_layers = 2 # 1 2 3
input_shape = 16
dropout = 0
dropout_factor = 0.3
